# Generated by Django 5.0.3 on 2024-10-11 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0005_remove_slide_caption_slide_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myprofile',
            name='desc',
            field=models.CharField(max_length=10000),
        ),
    ]
