# Generated by Django 3.2.12 on 2024-10-11 07:27

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0006_alter_myprofile_desc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='desc',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='myprofile',
            name='desc',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
