# Generated by Django 5.0.3 on 2024-10-15 03:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0010_auto_20241014_0456'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cmt',
            name='blog_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.blog'),
        ),
    ]
