# Generated by Django 4.2.4 on 2024-12-25 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0011_alter_cmt_blog_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cmt',
            name='blog_id',
            field=models.IntegerField(),
        ),
    ]
